### ISSUE TITLE
2022-02-15 meeting overview

### ISSUE THREAD

**Issue by MichalisPanayides** [MichalisPanayides/PhD-meetings#82]
# What has been done:
- Machine Learning course:
   - Week 5 ✔️ 
   - Week 6 ⌚ 
- EURO2022 - abstract ⌚ 
- Reinforcement Learning: 
   - Restructure code
   - Plot some form mean policy next to utility graph
   - Add limit on neighborhood size
   - Increase number of trials in simulation
- Minor changes:
   - (Arrival time * Servers) instead of (Service time / Servers)
   - Using utilisation instead of busy time
   - Using average simulated service time instead of service rate
- Game Paper new branch for first revisions

# To be discussed:
- Paper
   - [x] Annotated PDF
   - [x] Go through revisions
- RL algorithm
   - [ ] Utility functions
   - [ ] Make sure current run of the RL algorithm is appropriate
   - [ ] Some results

# To be done:
- Submit Researchfish review
- Continue ML course
- Abstract for EURO2022
- Abstract for CORS/INFORMS
- Continue RL algorithm
- Start working on Paper reviews
- Continue working on thesis structure

**Comment by MichalisPanayides** [comment]
# Todo list for next week:
- [x] Distractions, Risks, Recoveries -> Create vague abstract so that we can incorporate RL extension if needed
- [x] EURO 2022 -> Email with ORAHS code
- [x] Researchfish submission
- [ ] Paper - address the issues one by one
- [ ] RL algorithm - Continue playing around - NEW PARAMETERS (smaller model)
- [ ] Future things to keep in mind:
   - When service rate at a state is changed, change the surrounding states
   - Look at custom server priority
