### ISSUE TITLE
2022-02-22 meeting overview (Twosday!!)

### ISSUE THREAD

**Issue by MichalisPanayides** [MichalisPanayides/PhD-meetings#83]
# What has been done:
- ML course - Week 6 ✔️  
- Abstract for CORS/INFORMS ✔️ 
- Abstractfir EURO 2022 ✔️ 
- Researchfish submission ✔️ 
- Paper changes:
   - Change in vocabulary
   - Investigate problem parameters
- RL algorithm
   - More runs of the algorithm
   - Run with smaller sets of parameters

# To be discussed:
- [x] Paper - change in vocabulary (players -> hospitals) - 
   - **Current changes**:
      - *Players*: hospitals/EDs  (left it as *players* in some places)
      - *Distributor*: ambulance service/EMS
      - Sometimes refer to *Type 2 individuals* as **patients in ambulances**
   - **Current sections**:
      - Game overview section ✔️ 
      - Queueing model ❌❔
      - Methodology ✔️  
- [x] Paper - investigate effects of truncation (Unbounded vs N and M)
   - Simulation or Markov chains??
   - Waiting time, Blocking time, Proportion of individuals within time ✔️ 
- [x] RL algorithm
   - More examples with parameters similar to paper
   - Examples with smaller set of parameters

# To be done:
- Paper issues
- Submit CORS/INFORMS
- Submit EURO2022
- RL algorithm

**Comment by MichalisPanayides** [comment]
# Todo list for next week:
- [x] Distractions, Risks, Recoveries - Submit abstract
- [x] EURO 2022 - Submit abstract with ORAHS stream code
- Paper - address more issues
   - [x] Change vocabulary
      - Do not use ambulance patients. Use type 2 patients instead
      - Do not use waiting zone 1, 2 -> Use hospital, parking space
      - Clearly state what type 1 and type 2 patients are on game section, and include `TODO` to maybe move it to queue section
   - [x] Investigate effects of truncation
      - Include truncated simulation model in same graph
      - Get the time that each algorithm needs to run - Markov, Simulation (Bounded), Simulation (Unbounded)
- RL algorithm
    - [x] Run smaller model parameters for a longer amount of time
    - [x] Use a value of `e<0.5` - maybe closer to 0.1??
    - [ ] Plot results
- Future things to keep in mind:
   - Register to EURO
   - Register to CORS/INFORMS
   - When service rate at a state is changed, change the surrounding states
