### ISSUE TITLE
2022-03-01 meeting overview

### ISSUE THREAD

**Issue by MichalisPanayides** [MichalisPanayides/PhD-meetings#84]
# What has been done:
- ML course - Week 7 ✔️  
- Submit CORS/INFORMS abstract ✔️ 
- Submit EURO 2022 abstract ✔️ 
- Paper changes:
   - Change in vocabulary
   - Investigate problem parameters
- RL algorithm
   - Run scripts in siren
   - Run model for a longer period of time
   - Use additional e_parameter value of 0.1

# To be discussed:
- [x] EURO - CORS/INFORMS register either way?
- [x] Truncation effects plots
- [x] RL utility plots??

# To be done:
- Paper issues
- RL algorithm more utility plots

**Comment by MichalisPanayides** [comment]
# Todo list for next week:
- [ ] Distractions, Risks, Recoveries - Register (EXP1, EXP4, Risk Assessment, Submit)
- [ ] EURO 2022 - Register (EXP1, EXP4, Risk Assessment, Submit)
- [ ] Restructure paper
- Paper - address more issues
   - [x] Merge - change vocabulary PR
   - [x] Truncation effect
      - Get table for each algorithm runtime - Markov, Simulation (Bounded), Simulation (Unbounded)
- RL algorithm
    - [x] Run RL for x5 runtime for all e values
    - [x] Run RL with e = 0.2
    - [x] For e = 0.1:
       - [x] Start from different initial service rates μ = {0.1, 0.5, 1, ... }
          - We want to check if for different μ we get same policies (rates)
       - [x] Check increased/decreased arrival rate produces different results
    - [ ] Plot a 3rd graph with the impact of the server's behaviour on the hospital (waiting/blocking time)
    - [ ] Plot results
- Future things to keep in mind:
    - When service rate at a state is changed, change the surrounding states
