### ISSUE TITLE
2022-03-08 meeting overview

### ISSUE THREAD

**Issue by MichalisPanayides** [MichalisPanayides/PhD-meetings#85]
# What has been done:
- ML course - Week 8 ✔️  
- Paper changes:
   - Change vocabulary - merged ✔️
   - Times for truncated experiments ✔️
   - Restructure paper ⌚
- RL algorithm - more scripts in siren
   - Run RL for x5 runtime for all e values ⌚ 
   - Run RL with e = 0.2 ⌚
   - Start from different initial service rates μ = {0.1, 0.5, 1} ⌚
   - Check increased/decreased arrival rate produces different results ⌚

# To be discussed:
- *Reminder to self*: Record meeting
- Restructure paper
   - [x] New structure - overall structure
   - [x] Major contributions - Intro vs Lit. Review (p.4)
   - [x] Where to define what type 1 and type 2 individuals (p.7)
      - Is the definition fine? Non-urgent or non-emergency?
   - [x] Explain why the particular performance measures are needed? - (p.10)
   - [x] Better explanation of arriving state in blocking time section? - (p.12)
   - [x] Ambulance service VS EMS? Hospital VS ED? (p.16)
   - [x] $C_i$: number of healthcare professionals or number of beds - (p.17)
   - [x] Type 1, 2 individuals definition repeated (p.17)
   - [x] Methodology section - should there be a PoA section? (p.22 + p.24)
   - [x] Make *numerical results* section more oriented on flooded model - (p.23)
   - [x] Payoff matrices (x100) - (p.28)

# To be done:
- Paper issues
- RL algorithm more utility plots

**Comment by MichalisPanayides** [comment]
# Todo list for next week:
- [x] Submit for Greggynog
- [ ] Greggynog EXP4 form
- [ ] Distractions, Risks, Recoveries - Register (EXP1, EXP4, Risk Assessment, Submit)
- [ ] EURO 2022 - Register (EXP1, EXP4, Risk Assessment, Submit)
- [ ] Restructure paper
   - [x] Change section titles: A queueing model for the ED-EMS interface, Strategic manipulation of the ED-EMS interface
   - [x] Game subsections: 4.1 The model, 4.2 Results
       - Backwards induction becomes a sentence: ``We do this using backwards induction {throw couple of references} by first solving the game from the ambulance's point of view then from the hospital's point of view. One solution concept is N.E. {that becomes a paragraph and then another paragraph is...} another to be able to model the emergent behaviours is the learning algorithms and specifically the asymmetric replicator dynamics.
       - The way it is solved is first numerically for all pair of strategies we use the Brent's algorithm to find the BR of the ambulance center and that allow us to populate the utilities of all the hospitals because by solving the play of the EMS we know the arrival rate of every hospital which gives us this game. 
       - 1 line for backwards induction + 1 paragraph for N.E. + all equations for learning algorithm (maybe no change) 
    - [x] Major contributions - queue + performance measures + game + emergent behaviour
        - In literature review should address what other papers lack and it's covered here
    - [x] Type 1+2 individuals definitions
        - Type 2 individuals are patients arriving in ambulances who can be blocked (usually patients that are deemed not to be critical)
        - Define on queueing section + point at the definition on game section
    - [x] Arriving state in blocking time:
        - Fix typo
        - Remove the word model (-> system)
     - [x] $C_i$ use number of servers -> at the start say that servers can be either healthcare professionals OR beds
     - [x] EMS -> Ambulance service, ED -> hospital
     - [ ] Make payoff matrices on results section more readable
- RL algorithm (optional)
    - [ ] Plot results
    - [ ] Plot a 3rd graph with the impact of the server's behaviour on the hospital (waiting/blocking time)
- Future things to keep in mind:
    - Talk for Greggynog, Vancouver, Finland
    - When service rate at a state is changed, change the surrounding states
