### ISSUE TITLE
2022-03-22 meeting overview

### ISSUE THREAD

**Issue by MichalisPanayides** [MichalisPanayides/PhD-meetings#86]
# What has been done:
- ML course ✔️ 
- Documentation course - 2/3 ✔️
- JOSS review ⌚
- Paper:
   - Restructured paper ✔️
      - PR merged ✔️ 
   - Diagram of game theoretic model ✔️ 
   - Changes to conclusion: Major Contributions, Further work for Steady state
   - Truncation effect ✔️
- Thesis:
   - Queueing section ⌚
   - `git LFS` ✔️ 
- RL algorithm run:
   - Run scripts on siren ✔️
   - Collected from siren ✔️
   - Plot results ✔️
   - Results using x10 runtime ⌚
   - Results using different utility function ⌚

# To be discussed:
- [x] View restructured paper
- [x] Game theory diagram
- [x] Truncation effect VS explaining reason behind Fig 4 and 6
- Reinforcement Learning
   - [x] RL plots with increased runtime (+ variations)
   - [x] New utility function: `e * (proportion_of_inds_accepted) + (1 - e) * (idle time)`
   - [x] Should I delete data from siren?

# To be done:
- More paper issues
- RL algorithm

**Comment by MichalisPanayides** [comment]
# TODOs

- [x] Response to reviewers
   - [x] Initial
- [x] Danielle Workshop
- [x] New scripts
   - [x] Increased runtime
   - [x] Increase step of change
   - [x] Change utility function
   - [x] Run on siren
- [x] Address more paper issues
- [x] JOSS review
