### ISSUE TITLE
2023-01-25 meeting overview

### ISSUE THREAD

**Issue by MichalisPanayides** [MichalisPanayides/PhD-meetings#95]
# To be discussed:
- [x] Agent-based model
   - [x] Reinforcement Learning VS Agent-based?
   - [x] Structure
      - State-Dependent variation of queue ✔️
      - Server-dependent variation of queue ✔️
      - State-server-dependent variation of queue ✔️
      - Agent-based model description ❓ 
      - Case study ❓ 
      - Results ❓ 
- [x] Other chapters to be done
   - [x] Introduction 👍 
   - [x] Literature review 👍 
   - [x] Conclusion 👍 
   - Ethnography chapter ❓ 
   - `ambulance_game` library ❓ 
   - Open source software contribution ❓ 
   - Tests - CI - etc... ❓ 
- [x] Reference paper?

**Comment by MichalisPanayides** [comment]
# Agent based model chapter (Comments form the meeting)
- Use both the term Reinforcement Learning AND Agent-based model
   - Agent-based model refers to the individual agents and the environment that they interact with
   - Reinforcement Learning refers to the training and learning process of individuals
   - Chapter: `Extending to Agent-based model`
   - Section: `The agent-based model`
   - Section: `Reinforcement Learning`
- Other chapters:
   - **Lit review**: This chapter is based on the published findings of~\cite{Game theoretic paper}
   - **Ethnography chapter**: No form Vince (maybe have a paragraph in the agent-based model) - ask Paul's opinion
   - **`ambulance_game` library**: Appendix using Diataxis framework
   - **List of Open Source softwre contributions:** Add to the preamble (similar to list of figures/tables)
   - **Tests + CI + Documentation:** A paragraph in the introduction

**Comment by MichalisPanayides** [comment]
# TODO this week:
- Agent based model + Reinforcement Learning chapter
   - [x] Rename and restructure sections
   - [x] Write `Utility functions` section
   - [ ] Write `Reinforcement Learning` section
   - [ ] Write `Results` subsection
- [ ] Maybe work on the issues that are straightforward to fix

## Reward: Saturday + Sunday off
